### PR TITLE
Reformat code and change applicationId to popstellar

### PR DESCRIPTION
**Pull request by celinecamacho**

### CODE REVIEW

**Comment by celinecamacho** [comment]
The SonarCloud bugs are fixed in PR #427

**Review by pierluca — COMMENTED** [review]
Thanks so much for taking this on !

Tiny remark concerning changing applicationId: 
-> Shouldn't that also entail fixing the package names? 
-> How about the paths?

Maybe it's best to do this in a coordinated way with be1-go, which is trying to fix a similar problem, and drop the `student20_` and just call it `pop` so that we don't need to change it against next year. What did you decide on your end @nkcr ?

**Comment by pierluca** [comment]
As soon as the `applicationId` / package names things are fixed, I'm happy to merge this.

Careful though: you might have lots of merge conflicts with #427

**Comment by nkcr** [comment]
Result of discussing the applicationID with Pierluca: `pop` is too generic since it is a broad concept, and shouldn't be used for our particular implementation. Therefore, we agreed with the name **popstellar**, which refers to the concept of a N-version programing system implementing PoP, with its multiple inter-connected elements.

I'm going to update the go back-end with this name. The repos is left unchanged for the moment.

**Review by pierluca — CHANGES_REQUESTED** [review]
@celinecamacho  see message above by Noémien.
Please ensure that the folder names get updated too  (i.e. `src/main/java/com/github/dedis/popstellar/...` )

**Review by pierluca — APPROVED** [review]
As discussed, we can merge this now.

**Pull request merged**
