### PR TITLE
Election channel structure

### PR DESCRIPTION
**Pull request by flmichel**

### CODE REVIEW

**Review by Tesa27 — COMMENTED** [review]
This layout looks good and intuitive to me!

**Review by Tesa27 — DISMISSED** [review]

**Review by Tesa27 — COMMENTED** [review]
maybe change the type of ballotOptions from []string to []message.BallotOption but that's a detail

**Review by Tesa27 — COMMENTED** [review]
And let me know what you think, we could maybe change the type of `questions:` have a map where the id would be the key and the defined `question` type would be the value, I think it makes it easier to query/update `validVotes`

**Comment by flmichel** [comment]
> maybe change the type of ballotOptions from []string to []message.BallotOption and fhe type of method from string to message.PluralityMethod but that's a detail

Yes, good idea but I guess we have to wait that [#270](https://github.com/dedis/student_21_pop/pull/270) get accepted.

**Comment by flmichel** [comment]
> now what you think, we could maybe change the type of `questions:` have a map where the id would be the key and the defined `question` type would be the value, I think it makes it easier to query/update `validVotes`

I agree with that, I'm going to do the modifications!

**Pull request closed without merging**
