### PR TITLE
add tests for components CameraButton and WideButtonView

### PR DESCRIPTION
**Pull request by jiabaow**
I add tests for two already existing components (CameraButton and WideButtonView) to help me understand how the test works.

### CODE REVIEW

**Comment by jiabaow** [comment]
> [**PoP - Fe1-Web**] SonarCloud Quality Gate failed.    Quality Gate failed
> 
> [Bug](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=dedis_student_21_pop_fe1&pullRequest=572&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=dedis_student_21_pop_fe1&pullRequest=572&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=dedis_student_21_pop_fe1&pullRequest=572&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=dedis_student_21_pop_fe1&pullRequest=572&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=dedis_student_21_pop_fe1&pullRequest=572&metric=new_duplicated_lines_density&view=list)

How can I write tests for tests?

**Comment by pierluca** [comment]
@jiabaow You're writing tests, I don't think you need coverage on those :-) it's an issue of the CI, I'll merge after reviews.

**Review by Xelowak — APPROVED** [review]
Everything seems fine, but why does it contain Java code ?

**Comment by jiabaow** [comment]
> Everything seems fine, but why does it contain Java code ?
It's this problem I asked on Slack, they appear after I merged the master into this branch. Do you know a safe way to delete them?

**Review by pierluca — CHANGES_REQUESTED** [review]
Your test files LGTM.

Regarding the Git history and the merges with master:
I'm not sure what happened when merging from the master branch to your branch, but I would assume that during the merge process some files were changed (or kept from your branch as opposed to accepting the changes from master).
My guess would be that you handled the merge from the IDE and you didn't realize what the IDE was doing behind your back. I'd really suggest using the terminal for Git operations :-)

To fix this, I would suggest starting a **new branch** from master, doing a `git cherry-pick` of the changes you need (or even just copying the files you need from this branch with a `git checkout`).

Also, this branch still contains a wrong package.json / package-lock.json which references the React "non-Native" test rendering library. Make sure it's not in the final branch.

**Pull request closed without merging**
